version: '3.9'

volumes:
  postgres_data: { }

services:
  app:
    build: .
    expose:
      - "8000"
    user: "1000"
    volumes:
      - ./media:/wd/media:rw
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    env_file:
      - .env
    depends_on:
      - postgres
    profiles:
      - full_dev
    command: /start.sh

  postgres:
    image: postgres:15
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    profiles:
      - full_dev
      - local_dev

  nginx:
    build: ./docker/nginx
    ports:
      - "8080:8080"
    depends_on:
      - app