# Generated by Django 4.1.7 on 2023-03-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
            ],
        ),
    ]
