# Generated by Django 4.2 on 2023-04-08 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("translation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="text",
            new_name="data",
        ),
    ]
